apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus:9090
    basicAuth : false
    jsonData:
      timeInterval: '1m'
    editable: true
