modules:
      https_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: true
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          fail_if_ssl: true
          fail_if_not_ssl: false